/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Adesione { 
    id_adesione: string;
    id_soggetto: string;
    id_servizio: string;
    id_logico?: string;
    stato?: string;
    data_creazione: string;
    data_ultimo_aggiornamento?: string;
    utente_richiedente?: string;
    utente_ultimo_aggiornamento?: string;
}

