/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TipologiaAllegatoEnum } from './tipologiaAllegatoEnum';
import { VisibilitaAllegatoEnum } from './visibilitaAllegatoEnum';


export interface Allegato { 
    uuid: string;
    filename: string;
    estensione?: string;
    descrizione?: string;
    data: string;
    visibilita?: VisibilitaAllegatoEnum;
    tipologia?: TipologiaAllegatoEnum;
    url: string;
}
export namespace Allegato {
}


