/*
 * GovCat - GovWay API Catalogue
 * https://github.com/link-it/govcat
 *
 * Copyright (c) 2021-2026 Link.it srl (https://link.it).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3, as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIErogazione } from './aPIErogazione';
import { DocumentoCreate } from './documentoCreate';
import { ProtocolloEnum } from './protocolloEnum';
import { RuoloAPIEnum } from './ruoloAPIEnum';


export interface APICreate { 
    nome: string;
    versione: number;
    id_servizio: string;
    ruolo: RuoloAPIEnum;
    protocollo: ProtocolloEnum;
    profilo?: object;
    specifica?: DocumentoCreate;
    dati_erogazione?: APIErogazione;
    descrizione?: string;
}
export namespace APICreate {
}


