/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIErogazione } from './aPIErogazione';
import { DocumentoCreate } from './documentoCreate';
import { ProtocolloEnum } from './protocolloEnum';
import { RuoloAPIEnum } from './ruoloAPIEnum';


export interface APICreate { 
    nome: string;
    versione: number;
    id_servizio: string;
    ruolo: RuoloAPIEnum;
    protocollo: ProtocolloEnum;
    profilo?: object;
    specifica?: DocumentoCreate;
    dati_erogazione?: APIErogazione;
    descrizione?: string;
}
export namespace APICreate {
}


