/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComponentAuthTypeEnum } from './componentAuthTypeEnum';


export interface AuthTypeApiResource { 
    auth_type: ComponentAuthTypeEnum;
    resources?: Array<string>;
    profilo?: string;
    note?: string;
}
export namespace AuthTypeApiResource {
}


