/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Categoria { 
    id_tassonomia?: string;
    id_categoria?: string;
    id_categoria_padre?: string;
    label_tassonomia?: string;
    label_categoria?: string;
    descrizione?: string;
    immagine?: string;
    figli?: Array<Categoria>;
}

