/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfigurazioneUtente { 
    autoregistrazione_abilitata: boolean;
    autoabilitazione_abilitata: boolean;
    ruolo_da_idm_abilitato?: boolean;
    aggiornamento_idm_abilitato?: boolean;
}

