/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfigurazioneSoggetto { 
    codice_ente_abilitato: boolean;
    codice_fiscale_ente_abilitato: boolean;
    id_tipo_utente_abilitato: boolean;
}

