/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowProduzioneSenzaCollaudoEnum } from './workflowProduzioneSenzaCollaudoEnum';


export interface ConfigurazioneAdesione { 
    scelta_libera_organizzazione: boolean;
    riuso_client_obbligatorio: boolean;
    workflow_produzione_senza_collaudo: WorkflowProduzioneSenzaCollaudoEnum;
}
export namespace ConfigurazioneAdesione {
}


