/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemCategoria } from './itemCategoria';
import { DocumentoUpdate } from './documentoUpdate';

export interface DatiGenericiServizioUpdate { 
    gruppo?: string;
    descrizione: string;
    descrizione_sintetica: string;
    immagine?: DocumentoUpdate;
    tags?: Array<string>;
    tassonomie?: Array<ItemCategoria>;
    termini_ricerca?: string;
    note?: string;
    package: boolean;
}

