/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocumentoUpdate { 
    tipo_documento: DocumentoUpdate.TipoDocumentoEnum;
}
export namespace DocumentoUpdate {
    export type TipoDocumentoEnum = 'nuovo' | 'uuid';
    export const TipoDocumentoEnum = {
        Nuovo: 'nuovo' as TipoDocumentoEnum,
        Uuid: 'uuid' as TipoDocumentoEnum
    };
}


