/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VisibilitaEnum } from './visibilitaEnum';


export interface DominioUpdate { 
    nome: string;
    sogetto_referente?: string;
    visibilita: VisibilitaEnum;
    descrizione?: string;
}
export namespace DominioUpdate {
}


