/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VisibilitaEnum } from './visibilitaEnum';
import { TipoServizioEnum } from './tipoServizioEnum';

export interface IdentificativoServizioUpdate { 
    nome: string;
    versione: string;
    dominio: string;
    visibilita?: VisibilitaEnum;
    multi_adesione: boolean;
	tipo: TipoServizioEnum;
    skip_collaudo: boolean;
}
export namespace IdentificativoServizioUpdate {
}


