/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RuoloUtenteEnum } from './ruoloUtenteEnum';


export interface Idm { 
    principal?: string;
    sede?: string;
    ruoli?: Array<string>;
    ruolo_codificato?: RuoloUtenteEnum;
    nome?: string;
    cognome?: string;
    codice_fiscale?: string;
    email?: string;
    telefono?: string;
    matricola?: string;
}
export namespace Idm {
}


