/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentoApi } from './documentoApi';
import { TipoApiRisorsaEnum } from './tipoApiRisorsaEnum';
import { TipoApiEnum } from './tipoApiEnum';


export interface ListaRisorseApiRichiesta { 
    api_type: TipoApiEnum;
    content_type?: TipoApiRisorsaEnum;
    document?: DocumentoApi;
}
export namespace ListaRisorseApiRichiesta {
}


