/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Problem { 
    /**
     * Un testo di descrizione comprensibile del problema occorso
     */
    detail?: string;
    /**
     * Collegamento ad una specifica occorrenza dove si è verificato il problema
     */
    instance?: string;
    /**
     * Codice http restituito
     */
    status?: number;
    /**
     * Descrizione breve ed esplicativa del problema occorso
     */
    title?: string;
    /**
     * URI assoluta per la descrizione del problema occorso
     */
    type?: string;
}

