/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ProtocolloEnum = 'soap_11' | 'soap_12' | 'swagger_2' | 'openapi_3';

export const ProtocolloEnum = {
    Soap11: 'soap_11' as ProtocolloEnum,
    Soap12: 'soap_12' as ProtocolloEnum,
    Swagger2: 'swagger_2' as ProtocolloEnum,
    Openapi3: 'openapi_3' as ProtocolloEnum
};

