/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RuoloAPIEnum = 'erogato_soggetto_dominio' | 'erogato_soggetto_aderente';

export const RuoloAPIEnum = {
    Dominio: 'erogato_soggetto_dominio' as RuoloAPIEnum,
    Aderente: 'erogato_soggetto_aderente' as RuoloAPIEnum
};

