/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemCategoria } from './itemCategoria';
import { Documento } from './documento';
import { VisibilitaEnum } from './visibilitaEnum';


export interface Servizio { 
    id_servizio: string;
    nome: string;
    versione: string;
    stato: string;
    dominio: string;
    gruppo?: string;
    descrizione: string;
    descrizione_sintetica: string;
    immagine?: Documento;
    tags?: Array<string>;
    visibilita?: VisibilitaEnum;
    tassonomie?: Array<ItemCategoria>;
    termini_ricerca?: string;
    note?: string;
    multi_adesione: boolean;
    data_creazione: string;
    data_ultima_modifica?: string;
    utente_richiedente: string;
    utente_ultima_modifica?: string;
}
export namespace Servizio {
}


