/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemCategoria } from './itemCategoria';
import { ReferenteCreate } from './referenteCreate';
import { DocumentoCreate } from './documentoCreate';
import { VisibilitaEnum } from './visibilitaEnum';


export interface ServizioCreate { 
    nome: string;
    versione: string;
    dominio: string;
    gruppo?: string;
    referenti: Array<ReferenteCreate>;
    descrizione: string;
    descrizione_sintetica: string;
    immagine?: DocumentoCreate;
    tags?: Array<string>;
    visibilita?: VisibilitaEnum;
    tassonomie?: Array<ItemCategoria>;
    termini_ricerca?: string;
    note?: string;
    multi_adesione: boolean;
}
export namespace ServizioCreate {
}


