/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SoggettoUpdate { 
    nome: string;
    descrizione?: string;
    organizzazione: string;
    codice_ente?: string;
    codice_fiscale_soggetto?: string;
    id_tipo_utente?: string;
    referente: boolean;
    aderente: boolean;
}

