/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StatoProfiloEnum = 'sconosciuto' | 'non_configurato' | 'abilitato' | 'disabilitato';

export const StatoProfiloEnum = {
    Sconosciuto: 'sconosciuto' as StatoProfiloEnum,
    NonConfigurato: 'non_configurato' as StatoProfiloEnum,
    Abilitato: 'abilitato' as StatoProfiloEnum,
    Disabilitato: 'disabilitato' as StatoProfiloEnum
};

