/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StatoUtenteEnum = 'non_configurato' | 'abilitato' | 'disabilitato';

export const StatoUtenteEnum = {
    NonConfigurato: 'non_configurato' as StatoUtenteEnum,
    Abilitato: 'abilitato' as StatoUtenteEnum,
    Disabilitato: 'disabilitato' as StatoUtenteEnum
};

