/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Categoria } from './categoria';


export interface Tassonomia { 
    id_tassonomia: string;
    nome: string;
    descrizione: string;
    visible?: boolean;
    required?: boolean;
    immagine?: string;
    categoria_default?: string;
    categorie?: Array<Categoria>;
}

