/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TipoApiEnum = 'soap11' | 'soap12' | 'swagger_2' | 'openapi_3';

export const TipoApiEnum = {
    Soap11: 'soap11' as TipoApiEnum,
    Soap12: 'soap12' as TipoApiEnum,
    Swagger2: 'swagger_2' as TipoApiEnum,
    Openapi3: 'openapi_3' as TipoApiEnum
};

