/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type VisibilitaEnum = 'pubblico' | 'privato' | 'riservato';

export const VisibilitaEnum = {
    Pubblico: 'pubblico' as VisibilitaEnum,
    Privato: 'privato' as VisibilitaEnum,
    Riservato: 'riservato' as VisibilitaEnum
};

