/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type VisibilitaAllegatoEnum = 'pubblico' | 'adesione' | 'servizio' | 'gestore';

export const VisibilitaAllegatoEnum = {
    Pubblico: 'pubblico' as VisibilitaAllegatoEnum,
    Adesione: 'adesione' as VisibilitaAllegatoEnum,
    Servizio: 'servizio' as VisibilitaAllegatoEnum,
    Gestore: 'gestore' as VisibilitaAllegatoEnum
};

