/**
 * MODI - APICatalogo
 * Registrazione e Adesione alle API
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type WorkflowProduzioneSenzaCollaudoEnum = 'abilitato' | 'disabilitato' | 'link_altra_adesione';

export const WorkflowProduzioneSenzaCollaudoEnum = {
    Abilitato: 'abilitato' as WorkflowProduzioneSenzaCollaudoEnum,
    Disabilitato: 'disabilitato' as WorkflowProduzioneSenzaCollaudoEnum,
    LinkAltraAdesione: 'link_altra_adesione' as WorkflowProduzioneSenzaCollaudoEnum
};

